name: coffee_shop
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.2 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  convex_bottom_bar: ^3.2.0
  carousel_slider: ^4.2.1
  coupon_uikit: ^0.2.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/image/
    - assets/image/img_banner/
    - assets/image/image_product/